name: Latest blog post workflow
on: 
    schedule:
        - cron: '*/1 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: nikil-sri-shen/blog-post-workflow@master
              with: 
                max_post_count: "2"
                feed_list: "https://blogchaindaily.wordpress.com/"
